//! Codex-format output (`AGENTS.md`).

use crate::output::{generate_build_commands, group_notes_by_category};
use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::fmt::Write;
use std::path::PathBuf;

/// Common directories that should be excluded from AI operations.
const DEFAULT_BOUNDARIES: &[&str] = &[
    "node_modules",
    "target",
    "dist",
    ".git",
    "__pycache__",
    ".next",
    "build",
];

/// Formatter that produces an `AGENTS.md` file for OpenAI Codex.
pub struct CodexFormatter;

impl ContextFormatter for CodexFormatter {
    /// Render the project context as an `AGENTS.md` document.
    fn format(&self, ctx: &ProjectContext) -> Result<String, AppError> {
        let mut out = String::new();

        writeln!(out, "# AGENTS.md").map_err(fmt_err)?;
        writeln!(out, "> Auto-generated by ContextBridge. Do not edit manually.\n")
            .map_err(fmt_err)?;

        // Setup Commands
        write_setup_commands(&mut out, ctx)?;

        // Tech Stack
        write_tech_stack(&mut out, ctx)?;

        let groups = group_notes_by_category(&ctx.notes);

        // Coding Standards
        if let Some(notes) = groups.get("conventions") {
            writeln!(out, "## Coding Standards\n").map_err(fmt_err)?;
            for note in notes {
                writeln!(out, "### {}\n", note.title).map_err(fmt_err)?;
                writeln!(out, "{}\n", note.content).map_err(fmt_err)?;
            }
        }

        // Architecture
        if let Some(notes) = groups.get("architecture") {
            writeln!(out, "## Architecture\n").map_err(fmt_err)?;
            for note in notes {
                writeln!(out, "### {}\n", note.title).map_err(fmt_err)?;
                writeln!(out, "{}\n", note.content).map_err(fmt_err)?;
            }
        }

        // Boundaries
        write_boundaries(&mut out, &groups)?;

        // Recent Activity
        write_recent_activity(&mut out, ctx)?;

        Ok(out)
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "AGENTS.md"
    }

    /// Output directory (project root).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".")
    }
}

/// Write the setup commands section.
fn write_setup_commands(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let cmds = generate_build_commands(&ctx.tech_stack);
    if cmds.is_empty() {
        return Ok(());
    }

    writeln!(out, "## Setup Commands\n").map_err(fmt_err)?;
    writeln!(out, "```bash").map_err(fmt_err)?;
    for (label, cmd) in &cmds {
        writeln!(out, "# {label}").map_err(fmt_err)?;
        writeln!(out, "{cmd}").map_err(fmt_err)?;
    }
    writeln!(out, "```\n").map_err(fmt_err)?;
    Ok(())
}

/// Write a concise tech list.
fn write_tech_stack(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    if ctx.tech_stack.is_empty() {
        return Ok(());
    }
    writeln!(out, "## Tech Stack\n").map_err(fmt_err)?;
    for entry in &ctx.tech_stack {
        let version = entry
            .version
            .as_deref()
            .map(|v| format!(" v{v}"))
            .unwrap_or_default();
        writeln!(out, "- {}{} ({})", entry.name, version, entry.category).map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Write the boundaries section from notes or defaults.
fn write_boundaries(
    out: &mut String,
    groups: &std::collections::HashMap<&str, Vec<&contextbridge_core::ContextNote>>,
) -> Result<(), AppError> {
    writeln!(out, "## Boundaries\n").map_err(fmt_err)?;

    if let Some(notes) = groups.get("boundaries") {
        for note in notes {
            writeln!(out, "- {}", note.content.lines().next().unwrap_or_default())
                .map_err(fmt_err)?;
        }
    }

    for dir in DEFAULT_BOUNDARIES {
        writeln!(out, "- `{dir}/` — do not modify").map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Write the last 10 commits in concise format.
fn write_recent_activity(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    if ctx.recent_changes.is_empty() {
        return Ok(());
    }
    writeln!(out, "## Recent Activity\n").map_err(fmt_err)?;
    for change in ctx.recent_changes.iter().take(10) {
        let hash = change.commit_hash.as_deref().unwrap_or("");
        let short = hash.get(..7).unwrap_or(hash);
        writeln!(out, "- `{short}` {} — {}", change.change_type, change.summary)
            .map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Convert a `fmt::Error` into `AppError`.
fn fmt_err(e: std::fmt::Error) -> AppError {
    AppError::Other(e.to_string())
}
