//! Codex-format output (AGENTS.md).

use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::path::PathBuf;

/// Formatter that produces an `AGENTS.md` file for OpenAI Codex.
pub struct CodexFormatter;

impl ContextFormatter for CodexFormatter {
    /// Render the project context as an AGENTS.md document.
    fn format(&self, _ctx: &ProjectContext) -> Result<String, AppError> {
        // TODO: implement Codex-specific format
        Ok(String::from("# Agents instructions — auto-generated by ContextBridge\n"))
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "AGENTS.md"
    }

    /// Output directory (project root).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".")
    }
}
