//! Copilot-format output (`.github/copilot-instructions.md`).

use crate::output::group_notes_by_category;
use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::fmt::Write;
use std::path::PathBuf;

/// Formatter that produces a `copilot-instructions.md` file for GitHub Copilot.
pub struct CopilotFormatter;

impl ContextFormatter for CopilotFormatter {
    /// Render the project context as a `copilot-instructions.md` document.
    fn format(&self, ctx: &ProjectContext) -> Result<String, AppError> {
        let mut out = String::new();

        writeln!(out, "# Copilot Instructions — {}", ctx.project.name).map_err(fmt_err)?;
        writeln!(out, "> Auto-generated by ContextBridge. Do not edit manually.\n")
            .map_err(fmt_err)?;

        // About This Project
        write_about(&mut out, ctx)?;

        // Tech Stack
        write_tech_stack(&mut out, ctx)?;

        let groups = group_notes_by_category(&ctx.notes);

        // Coding Style
        if let Some(notes) = groups.get("conventions") {
            writeln!(out, "## Coding Style\n").map_err(fmt_err)?;
            for note in notes {
                writeln!(out, "### {}\n", note.title).map_err(fmt_err)?;
                writeln!(out, "{}\n", note.content).map_err(fmt_err)?;
            }
        }

        // What Copilot Should Do
        write_should_do(&mut out, &groups)?;

        // What Copilot Should Avoid
        write_should_avoid(&mut out, &groups)?;

        Ok(out)
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "copilot-instructions.md"
    }

    /// Output directory (`.github`).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".github")
    }
}

/// Write the "About This Project" section.
fn write_about(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let techs: Vec<&str> = ctx.tech_stack.iter().map(|t| t.name.as_str()).collect();
    writeln!(out, "## About This Project\n").map_err(fmt_err)?;
    if techs.is_empty() {
        writeln!(out, "Project located at `{}`.\n", ctx.project.root_path).map_err(fmt_err)?;
    } else {
        writeln!(
            out,
            "A project built with **{}**, located at `{}`.\n",
            techs.join(", "),
            ctx.project.root_path,
        )
        .map_err(fmt_err)?;
    }
    Ok(())
}

/// Write the tech stack as a bullet list with versions.
fn write_tech_stack(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    if ctx.tech_stack.is_empty() {
        return Ok(());
    }
    writeln!(out, "## Tech Stack\n").map_err(fmt_err)?;
    for entry in &ctx.tech_stack {
        let version = entry
            .version
            .as_deref()
            .map(|v| format!(" v{v}"))
            .unwrap_or_default();
        writeln!(out, "- **{}**{} ({})", entry.name, version, entry.category).map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Write the "What Copilot Should Do" section.
fn write_should_do(
    out: &mut String,
    groups: &std::collections::HashMap<&str, Vec<&contextbridge_core::ContextNote>>,
) -> Result<(), AppError> {
    writeln!(out, "## What Copilot Should Do\n").map_err(fmt_err)?;
    writeln!(out, "- Follow the project's established patterns and conventions").map_err(fmt_err)?;
    writeln!(out, "- Use the correct versions of libraries listed above").map_err(fmt_err)?;

    if let Some(notes) = groups.get("guidelines") {
        for note in notes {
            writeln!(out, "- {}", note.content.lines().next().unwrap_or_default())
                .map_err(fmt_err)?;
        }
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Write the "What Copilot Should Avoid" section.
fn write_should_avoid(
    out: &mut String,
    groups: &std::collections::HashMap<&str, Vec<&contextbridge_core::ContextNote>>,
) -> Result<(), AppError> {
    writeln!(out, "## What Copilot Should Avoid\n").map_err(fmt_err)?;
    writeln!(out, "- Don't suggest deprecated patterns").map_err(fmt_err)?;
    writeln!(out, "- Don't add dependencies not already in the project").map_err(fmt_err)?;

    for cat in &["avoid", "antipattern"] {
        if let Some(notes) = groups.get(cat) {
            for note in notes {
                writeln!(out, "- {}", note.content.lines().next().unwrap_or_default())
                    .map_err(fmt_err)?;
            }
        }
    }
    writeln!(out).map_err(fmt_err)?;
    Ok(())
}

/// Convert a `fmt::Error` into `AppError`.
fn fmt_err(e: std::fmt::Error) -> AppError {
    AppError::Other(e.to_string())
}
