//! Copilot-format output (`.github/copilot-instructions.md`).

use crate::output::{
    collect_boundary_hints, collect_important_paths, collect_workspace_manifests,
    display_workspace_dir, generate_build_commands_for_project, group_notes_by_category,
};
use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::fmt::Write;
use std::path::PathBuf;

/// Formatter that produces a `copilot-instructions.md` file for GitHub Copilot.
pub struct CopilotFormatter;

impl ContextFormatter for CopilotFormatter {
    /// Render the project context as a `copilot-instructions.md` document.
    fn format(&self, ctx: &ProjectContext) -> Result<String, AppError> {
        let mut out = String::new();

        writeln!(
            out,
            "# Copilot Instructions — {}",
            crate::output::sanitize_for_heading(&ctx.project.name)
        )?;
        writeln!(
            out,
            "> Auto-generated by ContextBridge. Do not edit manually.\n"
        )?;

        // About This Project
        write_about(&mut out, ctx)?;

        // Tech Stack
        write_tech_stack(&mut out, ctx)?;

        // Preferred Commands
        write_preferred_commands(&mut out, ctx)?;

        // Workspace Map
        write_workspace_map(&mut out, ctx)?;

        // Important Paths
        write_important_paths(&mut out, ctx)?;

        let groups = group_notes_by_category(&ctx.notes);

        // Coding Style
        if let Some(notes) = groups.get("conventions") {
            writeln!(out, "## Coding Style\n")?;
            for note in notes {
                writeln!(out, "### {}\n", note.title)?;
                writeln!(out, "{}\n", note.content)?;
            }
        }

        // What Copilot Should Do
        write_should_do(&mut out, ctx, &groups)?;

        // What Copilot Should Avoid
        write_should_avoid(&mut out, ctx, &groups)?;

        crate::output::check_output_limit(&mut out);
        Ok(out)
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "copilot-instructions.md"
    }

    /// Output directory (`.github`).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".github")
    }
}

/// Write the "About This Project" section.
fn write_about(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let techs: Vec<&str> = ctx.tech_stack.iter().map(|t| t.name.as_str()).collect();
    writeln!(out, "## About This Project\n")?;
    if techs.is_empty() {
        writeln!(out, "Project located at `{}`.\n", ctx.project.root_path)?;
    } else {
        writeln!(
            out,
            "A project built with **{}**, located at `{}`.\n",
            techs.join(", "),
            ctx.project.root_path,
        )?;
    }
    Ok(())
}

/// Write the tech stack as a bullet list with versions.
fn write_tech_stack(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    if ctx.tech_stack.is_empty() {
        return Ok(());
    }
    writeln!(out, "## Tech Stack\n")?;
    for entry in &ctx.tech_stack {
        let version = entry
            .version
            .as_deref()
            .map(|v| format!(" v{v}"))
            .unwrap_or_default();
        writeln!(out, "- **{}**{} ({})", entry.name, version, entry.category)?;
    }
    writeln!(out)?;
    Ok(())
}

fn write_preferred_commands(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let commands = generate_build_commands_for_project(&ctx.project.root_path, &ctx.tech_stack);
    if commands.is_empty() {
        return Ok(());
    }

    writeln!(out, "## Preferred Commands\n")?;
    writeln!(out, "```bash")?;
    for (label, command) in commands {
        writeln!(out, "# {label}")?;
        writeln!(out, "{command}")?;
    }
    writeln!(out, "```\n")?;
    Ok(())
}

fn write_workspace_map(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let workspaces = collect_workspace_manifests(&ctx.project.root_path);
    if workspaces.is_empty() {
        return Ok(());
    }

    writeln!(out, "## Workspace Map\n")?;
    for workspace in workspaces {
        let location = display_workspace_dir(&workspace.relative_dir);
        let manifest = workspace
            .package_name
            .as_ref()
            .map(|value| format!("{} ({value})", workspace.manifest_name))
            .unwrap_or_else(|| workspace.manifest_name.clone());
        writeln!(out, "- **{location}** — {manifest}")?;
    }
    writeln!(out)?;
    Ok(())
}

fn write_important_paths(out: &mut String, ctx: &ProjectContext) -> Result<(), AppError> {
    let important_paths = collect_important_paths(&ctx.project.root_path, &ctx.tech_stack);
    if important_paths.is_empty() {
        return Ok(());
    }

    writeln!(out, "## Important Paths\n")?;
    for entry in important_paths {
        writeln!(out, "- `{}` — {}", entry.path, entry.purpose)?;
    }
    writeln!(out)?;
    Ok(())
}

/// Write the "What Copilot Should Do" section.
fn write_should_do(
    out: &mut String,
    ctx: &ProjectContext,
    groups: &std::collections::BTreeMap<&str, Vec<&contextbridge_core::ContextNote>>,
) -> Result<(), AppError> {
    writeln!(out, "## What Copilot Should Do\n")?;
    writeln!(
        out,
        "- Follow the project's established patterns and conventions"
    )?;
    writeln!(out, "- Use the correct versions of libraries listed above")?;

    if collect_workspace_manifests(&ctx.project.root_path).len() > 1 {
        writeln!(
            out,
            "- Start from the closest workspace manifest before changing code, scripts, or dependencies"
        )?;
    }

    for hint in collect_boundary_hints(&ctx.project.root_path, &ctx.tech_stack) {
        writeln!(out, "- {hint}")?;
    }

    if let Some(notes) = groups.get("guidelines") {
        for note in notes {
            writeln!(out, "- {}", note.content.lines().next().unwrap_or_default())?;
        }
    }
    writeln!(out)?;
    Ok(())
}

/// Write the "What Copilot Should Avoid" section.
fn write_should_avoid(
    out: &mut String,
    ctx: &ProjectContext,
    groups: &std::collections::BTreeMap<&str, Vec<&contextbridge_core::ContextNote>>,
) -> Result<(), AppError> {
    writeln!(out, "## What Copilot Should Avoid\n")?;
    writeln!(out, "- Don't suggest deprecated patterns")?;
    writeln!(out, "- Don't add dependencies not already in the project")?;

    if collect_workspace_manifests(&ctx.project.root_path).len() > 1 {
        writeln!(
            out,
            "- Don't mix unrelated workspaces in one change unless the task clearly spans them"
        )?;
    }

    for cat in &["avoid", "antipattern"] {
        if let Some(notes) = groups.get(cat) {
            for note in notes {
                writeln!(out, "- {}", note.content.lines().next().unwrap_or_default())?;
            }
        }
    }
    writeln!(out)?;
    Ok(())
}
