//! Copilot-format output (.github/copilot-instructions.md).

use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::path::PathBuf;

/// Formatter that produces a `copilot-instructions.md` file for GitHub Copilot.
pub struct CopilotFormatter;

impl ContextFormatter for CopilotFormatter {
    /// Render the project context as a copilot-instructions.md document.
    fn format(&self, _ctx: &ProjectContext) -> Result<String, AppError> {
        // TODO: implement Copilot-specific format
        Ok(String::from("# Copilot instructions — auto-generated by ContextBridge\n"))
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "copilot-instructions.md"
    }

    /// Output directory (.github).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".github")
    }
}
