//! Cursor-format output (`.cursor/rules/contextbridge.mdc`).

use crate::output::{generate_globs_from_tech, group_notes_by_category};
use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::fmt::Write;
use std::path::PathBuf;

/// Formatter that produces a `contextbridge.mdc` file for Cursor IDE rules.
pub struct CursorFormatter;

impl ContextFormatter for CursorFormatter {
    /// Render the project context as a `.cursor/rules/contextbridge.mdc` document.
    fn format(&self, ctx: &ProjectContext) -> Result<String, AppError> {
        let mut out = String::new();
        let globs = generate_globs_from_tech(&ctx.tech_stack);

        // Front-matter
        writeln!(out, "---").map_err(fmt_err)?;
        writeln!(
            out,
            "description: Project context for {} — auto-generated by ContextBridge",
            ctx.project.name,
        )
        .map_err(fmt_err)?;
        writeln!(out, "globs: \"{globs}\"").map_err(fmt_err)?;
        writeln!(out, "alwaysApply: true").map_err(fmt_err)?;
        writeln!(out, "---\n").map_err(fmt_err)?;

        writeln!(out, "# {} Context\n", ctx.project.name).map_err(fmt_err)?;

        // Tech Stack
        if !ctx.tech_stack.is_empty() {
            writeln!(out, "## Tech Stack\n").map_err(fmt_err)?;
            for entry in &ctx.tech_stack {
                let version = entry
                    .version
                    .as_deref()
                    .map(|v| format!(" (v{v})"))
                    .unwrap_or_default();
                writeln!(out, "- **{}**{} — {}", entry.name, version, entry.category)
                    .map_err(fmt_err)?;
            }
            writeln!(out).map_err(fmt_err)?;
        }

        let groups = group_notes_by_category(&ctx.notes);

        // Coding Conventions
        if let Some(notes) = groups.get("conventions") {
            writeln!(out, "## Coding Conventions\n").map_err(fmt_err)?;
            for note in notes {
                writeln!(out, "### {}\n", note.title).map_err(fmt_err)?;
                writeln!(out, "{}\n", note.content).map_err(fmt_err)?;
            }
        }

        // Architecture Boundaries
        if let Some(notes) = groups.get("architecture") {
            writeln!(out, "## Architecture Boundaries\n").map_err(fmt_err)?;
            for note in notes {
                writeln!(out, "### {}\n", note.title).map_err(fmt_err)?;
                writeln!(out, "{}\n", note.content).map_err(fmt_err)?;
            }
        }

        Ok(out)
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "contextbridge.mdc"
    }

    /// Output directory (`.cursor/rules`).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".cursor/rules")
    }
}

/// Convert a `fmt::Error` into `AppError`.
fn fmt_err(e: std::fmt::Error) -> AppError {
    AppError::Other(e.to_string())
}
