//! Cursor-format output (`.cursor/rules/contextbridge.mdc`).

use crate::output::{generate_globs_from_tech, group_notes_by_category};
use contextbridge_core::{AppError, ContextFormatter, ProjectContext};
use std::fmt::Write;
use std::path::PathBuf;

/// Formatter that produces a `contextbridge.mdc` file for Cursor IDE rules.
pub struct CursorFormatter;

impl ContextFormatter for CursorFormatter {
    /// Render the project context as a `.cursor/rules/contextbridge.mdc` document.
    fn format(&self, ctx: &ProjectContext) -> Result<String, AppError> {
        let mut out = String::new();
        let globs = generate_globs_from_tech(&ctx.tech_stack);

        // Front-matter
        writeln!(out, "---")?;
        writeln!(
            out,
            "description: Project context for {} — auto-generated by ContextBridge",
            crate::output::sanitize_for_yaml(&ctx.project.name),
        )
        ?;
        writeln!(out, "globs: \"{globs}\"")?;
        writeln!(out, "alwaysApply: true")?;
        writeln!(out, "---\n")?;

        writeln!(
            out,
            "# {} Context\n",
            crate::output::sanitize_for_heading(&ctx.project.name)
        )
        ?;

        // Tech Stack
        if !ctx.tech_stack.is_empty() {
            writeln!(out, "## Tech Stack\n")?;
            for entry in &ctx.tech_stack {
                let version = entry
                    .version
                    .as_deref()
                    .map(|v| format!(" (v{v})"))
                    .unwrap_or_default();
                writeln!(out, "- **{}**{} — {}", entry.name, version, entry.category)
                    ?;
            }
            writeln!(out)?;
        }

        let groups = group_notes_by_category(&ctx.notes);

        // Coding Conventions
        if let Some(notes) = groups.get("conventions") {
            writeln!(out, "## Coding Conventions\n")?;
            for note in notes {
                writeln!(out, "### {}\n", note.title)?;
                writeln!(out, "{}\n", note.content)?;
            }
        }

        // Architecture Boundaries
        if let Some(notes) = groups.get("architecture") {
            writeln!(out, "## Architecture Boundaries\n")?;
            for note in notes {
                writeln!(out, "### {}\n", note.title)?;
                writeln!(out, "{}\n", note.content)?;
            }
        }

        crate::output::check_output_limit(&mut out);
        Ok(out)
    }

    /// Output file name.
    fn output_filename(&self) -> &str {
        "contextbridge.mdc"
    }

    /// Output directory (`.cursor/rules`).
    fn output_directory(&self) -> PathBuf {
        PathBuf::from(".cursor/rules")
    }
}

